apiVersion: batch/v1
kind: CronJob
metadata:
  name: echo-date-minimal
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: echo
              image: busybox:1.36.1
              command: ["date"]
          restartPolicy: Never
      backoffLimit: 1
