apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-rwo
allowVolumeExpansion: true
parameters:
  type: pd-balanced
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
