version: 3

tasks:
  01-install-trivy-operator:
    desc: "Install trivy operator into trivy-system namespace"
    cmds:
      - helm repo add aqua https://aquasecurity.github.io/helm-charts/
      - helm repo update
      - |
        helm upgrade --install trivy-operator aqua/trivy-operator \
          --namespace trivy-system \
          --create-namespace \
          --version 0.23.2

  02-uninstall-trivy-operator:
    desc: "Uninstall the trivy operator"
    cmds:
      - helm uninstall trivy-operator --namespace trivy-system
