apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: external-secrets
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store # name of the SecretStore (or kind specified)
  target:
    name: external-secrets-example-k8s # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: key-k8s # key in the Kubernetes Secret
      remoteRef:
        key: external-secrets-example-gcp # name of the GCPSM secret key
