apiVersion: batch/v1
kind: Job
metadata:
  name: no-permissions
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: cgr.dev/chainguard/kubectl
          args: ["get", "pods", "-A"]
      restartPolicy: Never
  backoffLimit: 1
