version: "3"

includes:
  external-secrets-operator:
    taskfile: ./external-secrets-operator/Taskfile.yaml
    dir: ./external-secrets-operator

  tilt:
    taskfile: ./tilt/Taskfile.yaml
    dir: ./tilt
